name: Optimize SVGs
on: [pull_request]
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SVGO Action
        uses: calibreapp/svgo-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svgo_config: svgo.config.js
